// Données du jardin de Cookie Clicker
// mature  = nombre de ticks avant maturation (valeur de ta feuille d'optimisation)
// window  = nombre de ticks de vie APRÈS maturité avant disparition  (-1 = immortelle)
// modif   = true => durée notable / modifiable (le 2e "+" de ta notation)
// marker  = marqueur de ta feuille (¹ ² ³ W J) pour les groupes / variantes
// group   = 1 (plantes prioritaires) / 2 (autres plantes), tel que dans ta liste
// checked = état de départ de la case (sera ensuite mémorisé dans le navigateur)
// effect / mutation / cost viennent du wiki (https://cookieclicker.wiki.gg/wiki/Garden)

const PLANTS = [
  // ---------- GROUPE 1 ----------
  { en: "Baker's Wheat", fr: "Blé du pâtissier", mature: 5, window: 8, modif: false, marker: "", group: 1, checked: true,
    effect: "+1% CpS", mutation: "Plante de départ", cost: "1 min de CpS" },
  { en: "Bakeberry", fr: "Pâtisetille", mature: 32, window: 35, modif: false, marker: "", group: 1, checked: true,
    effect: "+1% CpS ; récolte → +30 min de CpS", mutation: "2× Blé du pâtissier (rare)", cost: "45 min de CpS" },
  { en: "Thumbcorn", fr: "Maïspouce", mature: 3, window: 12, modif: false, marker: "", group: 1, checked: true,
    effect: "+2% cookies par clic", mutation: "2× Blé du pâtissier", cost: "5 min de CpS" },
  { en: "Cronerice", fr: "Mégèriz", mature: 70, window: 64, modif: true, marker: "", group: 1, checked: true,
    effect: "+3% CpS des mamies", mutation: "Blé + Maïspouce", cost: "15 min de CpS" },
  { en: "Gildmillet", fr: "Gildmillet", mature: 14, window: 23, modif: false, marker: "", group: 1, checked: true,
    effect: "+1% gains cookies dorés, +0,1% durée", mutation: "Mégèriz + Maïspouce", cost: "15 min de CpS" },
  { en: "Ordinary Clover", fr: "Trèfle Ordinaire", mature: 20, window: 38, modif: false, marker: "", group: 1, checked: true,
    effect: "+1% fréquence cookies dorés", mutation: "Blé + Gildmillet", cost: "25 min de CpS" },
  { en: "Shimmerlily", fr: "Lys Irisé", mature: 9, window: 4, modif: false, marker: "", group: 1, checked: true,
    effect: "+1% gains / fréquence / drops cookies dorés", mutation: "Trèfle + Gildmillet", cost: "60 min de CpS" },
  { en: "Elderwort", fr: "Odeurweiss", mature: 156, window: -1, modif: true, marker: "", group: 1, checked: true,
    effect: "+1% gains/fréquence wrath, +1% CpS mamies ; vieillit l'entourage de 3%", mutation: "Lys Irisé + Mégèriz", cost: "180 min de CpS" },
  { en: "Ichorpuff", fr: "Vesse d'Ichor", mature: 20, window: 38, modif: false, marker: "²", group: 1, checked: true,
    effect: "L'entourage vieillit 2× moins vite, mais 50% moins efficace", mutation: "Odeurweiss + Sporemiette", cost: "120 min de CpS" },
  { en: "Golden Clover", fr: "Trèfle Doré", mature: 5, window: 5, modif: true, marker: "", group: 1, checked: false,
    effect: "+3% fréquence cookies dorés", mutation: "Blé + Gildmillet (très rare) ou 4× Trèfle", cost: "125 min de CpS" },

  // ---------- GROUPE 2 ----------
  { en: "Meddleweed", fr: "Indiscrerbe", mature: 4, window: 4, modif: false, marker: "", group: 2, checked: true,
    effect: "Aucun effet ; peut envahir les plantes voisines", mutation: "Apparaît sur les cases vides", cost: "1 min de CpS" },
  { en: "Brown Mold", fr: "Moisissure brune", mature: 5, window: 3, modif: false, marker: "¹", group: 2, checked: true,
    effect: "-1% CpS ; peut se répandre en mildou blanc", mutation: "Mildou blanc + Moisissure brune", cost: "20 min de CpS" },
  { en: "Crumbspore", fr: "Sporemiette", mature: 14, window: 9, modif: false, marker: "²", group: 2, checked: true,
    effect: "Explose en jusqu'à 1 min de CpS ; peut envahir", mutation: "Apparaît seule / 2× Champipâte", cost: "10 min de CpS" },
  { en: "White Mildew", fr: "Mildou blanc", mature: 5, window: 3, modif: false, marker: "³", group: 2, checked: true,
    effect: "+1% CpS ; peut se répandre en moisissure brune", mutation: "Moisissure brune + mildou", cost: "20 min de CpS" },
  { en: "Chocoroot", fr: "Chocoracine", mature: 6, window: 19, modif: false, marker: "¹", group: 2, checked: true,
    effect: "+1% CpS ; récolte → +3 min ; croissance prévisible", mutation: "Blé + Moisissure brune", cost: "15 min de CpS" },
  { en: "Queenbeet", fr: "Bettereine", mature: 64, window: 20, modif: true, marker: "", group: 2, checked: true,
    effect: "+0,3% durée dorés, -2% CpS ; récolte → +1 h de CpS", mutation: "Pâtisetille + Chocoracine", cost: "90 min de CpS" },
  { en: "White Chocoroot", fr: "Chocoracine blanche", mature: 6, window: 19, modif: false, marker: "W", group: 2, checked: true,
    effect: "+1% gains dorés ; récolte → +3 min", mutation: "Chocoracine + Mildou blanc", cost: "15 min de CpS" },
  { en: "Wrinklegill", fr: "Ridegibier", mature: 25, window: 15, modif: false, marker: "²", group: 2, checked: true,
    effect: "Les wrinklers apparaissent 2% plus vite, digèrent 1% de plus", mutation: "Sporemiette + Moisissure brune", cost: "20 min de CpS" },
  { en: "Tidygrass", fr: "Proprerbe", mature: 76, window: 124, modif: true, marker: "", group: 2, checked: true,
    effect: "La zone 5×5 ne développe ni mauvaise herbe ni champignon", mutation: "Blé + Chocoracine blanche", cost: "90 min de CpS" },
  { en: "Glovemorel", fr: "Gantomorille", mature: 7, window: 2, modif: false, marker: "²", group: 2, checked: true,
    effect: "+4% clics, +1% CpS curseurs, -1% CpS", mutation: "Sporemiette + Maïspouce", cost: "30 min de CpS" },
  { en: "Cheapcap", fr: "Capacher", mature: 3, window: 5, modif: false, marker: "", group: 2, checked: true,
    effect: "Bâtiments 0,2% moins chers", mutation: "Sporemiette + Lys Irisé", cost: "40 min de CpS" },
  { en: "Doughshroom", fr: "Champipâte", mature: 41, window: 9, modif: false, marker: "²", group: 2, checked: true,
    effect: "Explose en jusqu'à 5 min de CpS ; peut envahir", mutation: "2× Sporemiette", cost: "100 min de CpS" },
  { en: "Green Rot", fr: "Vertiture", mature: 4, window: 2, modif: false, marker: "³", group: 2, checked: true,
    effect: "+0,5% durée dorés, +1% fréquence, +1% drops", mutation: "Mildou blanc + Trèfle", cost: "60 min de CpS" },
  { en: "Keenmoss", fr: "Poussemousse", mature: 10, window: 6, modif: false, marker: "¹", group: 2, checked: true,
    effect: "+3% drops aléatoires", mutation: "Vertiture + Moisissure brune", cost: "50 min de CpS" },
  { en: "Wardlichen", fr: "Gardelichen", mature: 9, window: 6, modif: false, marker: "", group: 2, checked: true,
    effect: "-2% cookies wrath, wrinklers 15% plus lents", mutation: "Mégèriz + Poussemousse", cost: "10 min de CpS" },
  { en: "Drowsyfern", fr: "Ronflegère", mature: 285, window: 715, modif: true, marker: "", group: 2, checked: false,
    effect: "+3% CpS, -5% clics, -10% fréquence dorés", mutation: "Chocoracine + Poussemousse", cost: "90 min de CpS" },
  { en: "Fool's Bolete", fr: "Bolet Sleula", mature: 3, window: 6, modif: false, marker: "", group: 2, checked: true,
    effect: "+2% fréquence dorés, -5% gains, -2% durée", mutation: "Champipâte + Vertiture", cost: "15 min de CpS" },
  { en: "Whiskerbloom", fr: "Moustafleur", mature: 19, window: 15, modif: false, marker: "", group: 2, checked: true,
    effect: "+0,2% des effets du lait", mutation: "Lys Irisé + Chocoracine blanche", cost: "20 min de CpS" },
  { en: "Nursetulip", fr: "Nutrilipe", mature: 38, window: 29, modif: false, marker: "", group: 2, checked: true,
    effect: "Entourage 20% plus efficace, -2% CpS", mutation: "2× Moustafleur", cost: "40 min de CpS" },
  { en: "Chimerose", fr: "Tinterose", mature: 17, window: 41, modif: false, marker: "", group: 2, checked: true,
    effect: "+1% gains / fréquence rennes", mutation: "Lys Irisé + Moustafleur", cost: "15 min de CpS" },
  { en: "Duketater", fr: "Ducdeterre", mature: 201, window: 22, modif: true, marker: "", group: 2, checked: false,
    effect: "Récolte → +2 h de CpS", mutation: "2× Bettereine", cost: "480 min de CpS" },
  { en: "Shriekbulb", fr: "Bulburieur", mature: 17, window: 12, modif: false, marker: "", group: 2, checked: true,
    effect: "-2% CpS, entourage 5% moins efficace", mutation: "Ducdeterre / Champipâte / Odeurweiss", cost: "60 min de CpS" },
  { en: "Juicy Queenbeet", fr: "Bettereine juteuse", mature: 1010, window: 240, modif: true, marker: "J", group: 2, checked: false,
    effect: "-10% CpS, entourage 20% moins efficace ; récolte → +1 sucre", mutation: "8× Bettereine autour", cost: "Ne se plante pas" },
  { en: "Everdaisy", fr: "Toujoursguerite", mature: 238, window: -1, modif: true, marker: "", group: 2, checked: false,
    effect: "Zone 3×3 sans mauvaise herbe ; immortelle", mutation: "3× Proprerbe + 3× Odeurweiss", cost: "180 min de CpS" },
];
